---
title: Test properties of limma-based routines
---

```{r}
set.seed(1234)

library(tidyverse)
library(limma)
devtools::load_all("..")

n <- 100
folds <- seq(-2,2,length.out=n)
row_means <- runif(n, min=0, max=5)
means <- outer(folds, c(-1,-1,1,1)) + row_means
sds <- rep(runif(n, min=0,max=2), 4)
mat <- rnorm(length(means), mean=means, sd=sds)
dim(mat) <- dim(means) 

mat

design <- cbind(c(1,1,0,0), c(0,0,1,1))

fit <- lmFit(mat, design)
cfit <- contrasts.fit(fit, contrasts=c(-1,1))

eBayes(fit)$df.prior

# Using our version of limma's treat
confects_standard <- limma_confects(cfit, coef=1)
# Using limma's treat
confects_limma <- topconfects:::limma_confects_limma(cfit, coef=1)

confects_standard
confects_limma
```

Our version of limma TREAT and limma's native TREAT p values should be identical.

```{r}
for(lfc in c(0.5, 1.0, 2.0)) {
    p <- confects_standard$pfunc(1:n, lfc)
    p_limma <- confects_limma$pfunc(1:n, lfc)
    print(identical(p, p_limma))
    plot(p, p_limma, main=paste("lfc",lfc))
    abline(0,1)
}
```
